// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/*
  ASLDelegationChain.sol

  Privacy-preserving payment delegation chain.
  All monetary values are hidden behind Poseidon commitments.
  Two Groth16 proofs per allocation:
    - Upstream proof:   proves remaining decreases correctly
    - Downstream proof: proves child amount equals delta
  Chain verifies both proofs share the same commitmentDelta,
  linking them without revealing the actual amount.

  Nothing public on-chain except cryptographic commitments.
*/

interface IGroth16Verifier {
    function verifyProof(
        uint[2]    calldata _pA,
        uint[2][2] calldata _pB,
        uint[2]    calldata _pC,
        uint[]     calldata _pubSignals
    ) external view returns (bool);
}

contract ASLDelegationChain {

    // ── Verifier contracts (generated by snarkjs from circuits) ──
    IGroth16Verifier public immutable upstreamVerifier;
    IGroth16Verifier public immutable downstreamVerifier;

    // ── On-chain node state (public — commitments only) ──────────
    struct Node {
        uint256 amountCommitment;      // Poseidon(amount, blind)    — fixed once set
        uint256 remainingCommitment;   // Poseidon(remaining, blind) — updated per child
        bytes32 parentId;
        address holder;
        uint64  createdAt;
        bool    active;
    }

    mapping(bytes32 => Node)    public nodes;
    mapping(uint256 => bool)    public usedNullifiers;
    mapping(bytes32 => bytes32[]) public children;

    uint256 public totalNodes;

    // ── Events ────────────────────────────────────────────────────
    event RootCreated(
        bytes32 indexed nodeId,
        address indexed holder,
        uint256 amountCommitment,
        uint256 remainingCommitment
    );

    event NodeAllocated(
        bytes32 indexed nodeId,
        bytes32 indexed parentId,
        uint256 amountCommitment,
        uint256 remainingCommitment,
        uint256 commitmentDelta       // on-chain: Poseidon(delta, blind) — no value
    );

    event RemainingUpdated(
        bytes32 indexed nodeId,
        uint256 oldRemainingCommitment,
        uint256 newRemainingCommitment
    );

    event PaymentRecorded(
        bytes32 indexed nodeId,
        uint256 nullifier
    );

    // ── Constructor ───────────────────────────────────────────────
    constructor(
        address _upstreamVerifier,
        address _downstreamVerifier
    ) {
        upstreamVerifier   = IGroth16Verifier(_upstreamVerifier);
        downstreamVerifier = IGroth16Verifier(_downstreamVerifier);
    }

    // ── Root entity (Mastercard) creates initial commitment ───────
    // No proof needed — root self-authorises
    function createRoot(
        uint256 amountCommitment,
        uint256 remainingCommitment
    ) external returns (bytes32 nodeId) {
        nodeId = keccak256(abi.encode(
            amountCommitment,
            block.timestamp,
            msg.sender,
            totalNodes
        ));

        nodes[nodeId] = Node({
            amountCommitment:    amountCommitment,
            remainingCommitment: remainingCommitment,
            parentId:            bytes32(0),
            holder:              msg.sender,
            createdAt:           uint64(block.timestamp),
            active:              true
        });

        totalNodes++;

        emit RootCreated(nodeId, msg.sender, amountCommitment, remainingCommitment);
    }

    // ── Allocate to child — requires BOTH proofs ─────────────────
    /*
      Upstream proof public signals:  [commitmentBefore, commitmentAfter, commitmentDelta]
      Downstream proof public signals: [commitmentAmount, commitmentDelta]

      The chain checks:
        1. upstream proof is valid
        2. downstream proof is valid
        3. commitmentDelta matches in BOTH proofs — links them without revealing delta
        4. commitmentBefore matches current on-chain remainingCommitment
    */
    function allocate(
        // Parent node
        bytes32 parentId,

        // Upstream proof (runs in parent entity's system)
        uint256 newParentRemainingCommitment,
        uint256 commitmentDelta,
        uint[2]    calldata upPiA,
        uint[2][2] calldata upPiB,
        uint[2]    calldata upPiC,

        // Downstream proof (runs in child entity's system)
        uint256 childAmountCommitment,
        uint256 childRemainingCommitment,
        uint[2]    calldata downPiA,
        uint[2][2] calldata downPiB,
        uint[2]    calldata downPiC

    ) external returns (bytes32 childId) {

        Node storage parent = nodes[parentId];
        require(parent.active,                    "Parent node not found");
        require(parent.remainingCommitment != 0,  "Parent has no remaining");

        // ── Verify upstream proof ─────────────────────────────────
        // Public signals: [commitmentBefore, commitmentAfter, commitmentDelta]
        uint[] memory upSignals = new uint[](3);
        upSignals[0] = parent.remainingCommitment;    // must match current on-chain
        upSignals[1] = newParentRemainingCommitment;
        upSignals[2] = commitmentDelta;

        require(
            upstreamVerifier.verifyProof(upPiA, upPiB, upPiC, upSignals),
            "Upstream proof invalid"
        );

        // ── Verify downstream proof ───────────────────────────────
        // Public signals: [commitmentAmount, commitmentDelta]
        // commitmentDelta MUST match the upstream proof — chain enforces linkage
        uint[] memory downSignals = new uint[](2);
        downSignals[0] = childAmountCommitment;
        downSignals[1] = commitmentDelta;         // same value — chain checks this

        require(
            downstreamVerifier.verifyProof(downPiA, downPiB, downPiC, downSignals),
            "Downstream proof invalid"
        );

        // ── Both proofs valid — update state ──────────────────────
        uint256 oldRemaining = parent.remainingCommitment;
        parent.remainingCommitment = newParentRemainingCommitment;

        emit RemainingUpdated(parentId, oldRemaining, newParentRemainingCommitment);

        // ── Create child node ─────────────────────────────────────
        childId = keccak256(abi.encode(
            childAmountCommitment,
            parentId,
            block.timestamp,
            totalNodes
        ));

        nodes[childId] = Node({
            amountCommitment:    childAmountCommitment,
            remainingCommitment: childRemainingCommitment,
            parentId:            parentId,
            holder:              msg.sender,
            createdAt:           uint64(block.timestamp),
            active:              true
        });

        children[parentId].push(childId);
        totalNodes++;

        emit NodeAllocated(
            childId,
            parentId,
            childAmountCommitment,
            childRemainingCommitment,
            commitmentDelta
        );
    }

    // ── Getter helpers ────────────────────────────────────────────
    function getNode(bytes32 nodeId) external view returns (Node memory) {
        return nodes[nodeId];
    }

    function getChildren(bytes32 nodeId) external view returns (bytes32[] memory) {
        return children[nodeId];
    }

    function nodeExists(bytes32 nodeId) external view returns (bool) {
        return nodes[nodeId].active;
    }
}
