import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Shield, Snowflake, Ban, CheckCircle2, AlertTriangle, Network, FileKey2, Receipt, GitBranch, Play, RotateCcw, Database, Eye, LockKeyhole, Send, Landmark, UserRoundCog } from 'lucide-react';
import './styles.css';

const day = 86400000;
const base = Date.UTC(2026, 0, 1);
const dt = (n) => new Date(n).toISOString().slice(0,10);
const money = (v) => Number(v || 0);
const hash = (s) => '0x' + Array.from(new TextEncoder().encode(s)).map(b=>b.toString(16).padStart(2,'0')).join('').padEnd(64,'0').slice(0,64);
const commit = (label, value) => hash(`${label}:private=${value}:blind=${crypto.getRandomValues(new Uint32Array(2)).join('-')}`);
const period = (s,e) => ({ startAt: base+s*day, endAt: base+e*day, settlementDeadline: base+(e+2)*day });
const blank = { program:null, businesses:[], agents:[], receivables:[], batches:[], nullifiers:[], events:[], frozen:false, terminated:false, privateLedger:{} };
const ev = (type,text,data={}) => ({ id:`EVT-${Date.now()}-${Math.random().toString(16).slice(2,6)}`, at:new Date().toLocaleTimeString(), type, text, data });
const short = (v) => v ? `${v.slice(0,18)}…` : '—';
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Badge({status}){return <span className={'badge '+String(status).toLowerCase().replaceAll(' ','-')}>{status}</span>}
function Input({label,...props}){return <label className="field"><span>{label}</span><input {...props}/></label>}
function Select({label,children,...props}){return <label className="field"><span>{label}</span><select {...props}>{children}</select></label>}
function TextArea({label,...props}){return <label className="field"><span>{label}</span><textarea {...props}/></label>}
function AdminAmountNote(){return <em className="muted">private amount hidden — commitment only</em>}

function Graph({s}){
  if(!s.program) return <div className="empty"><Play/>Start by creating the Mastercard → PSP authorization.</div>;
  return <div className="graph"><div className="node root"><Shield/>Mastercard Program<br/><small>{s.program.id}</small></div><div className="branch businessBranch">{s.businesses.map(b=><div className="branchCol" key={b.id}><div className="edge">PSP funds</div><div className="node business"><Landmark/>{b.name}<br/><small>{b.id}</small></div>{s.agents.filter(a=>a.parentId===b.id).map(a=><div key={a.id}><div className="edge tiny">purpose: {a.purpose}</div><div className="node agent"><GitBranch/>{a.name}<br/><small>{a.id}</small></div>{s.receivables.filter(r=>r.parentId===a.id).map(r=><div key={r.id}><div className="edge tiny">merchant payment</div><div className="node merchant"><Receipt/>{r.merchant}<br/><small>{r.id}</small></div></div>)}</div>)}</div>)}</div></div>
}

function DemoActions({s,setS}){
  const [programAmount,setProgramAmount]=useState('1000000');
  const [businessName,setBusinessName]=useState('RetailCo');
  const [businessAmount,setBusinessAmount]=useState('250000');
  const [agentName,setAgentName]=useState('North Route Agent');
  const [agentPurpose,setAgentPurpose]=useState('Regional merchant acquisition');
  const [agentAmount,setAgentAmount]=useState('50000');
  const [merchantName,setMerchantName]=useState('Merchant One');
  const [merchantAmount,setMerchantAmount]=useState('12000');
  const [selectedBusiness,setSelectedBusiness]=useState('');
  const [selectedAgent,setSelectedAgent]=useState('');
  const [notice,setNotice]=useState('');
  const update = (fn) => setS(prev => fn(structuredClone(prev)));
  const businessUsed = (state,bid) => state.agents.filter(a=>a.parentId===bid).reduce((n,a)=>n+(state.privateLedger[a.id]?.amount||0),0);
  const agentUsed = (state,aid) => state.receivables.filter(r=>r.parentId===aid).reduce((n,r)=>n+(state.privateLedger[r.id]?.amount||0),0);
  function createProgram(){ const amt=money(programAmount); if(amt<=0) return setNotice('Program amount must be positive.'); update(st=>{ const p={id:'MC-PROG-001',role:'Mastercard → PSP',name:'Mastercard authorizes Blue PSP',status:'Active',psp:'Blue PSP',commitment:commit('program-envelope',amt),policyHash:hash('program-policy-v2'),...period(0,180)}; st.program=p; st.privateLedger[p.id]={amount:amt}; st.events.unshift(ev('PROGRAM_CREATED','Private PSP envelope validated and committed. Actual amount is not shown in admin.',{id:p.id,commitment:p.commitment})); return st;}); setNotice('Program authorization created. Admin sees commitment only.'); }
  function createBusiness(){ const amt=money(businessAmount); if(!s.program) return setNotice('Create PSP program first.'); if(s.frozen||s.terminated) return setNotice('Program is frozen/terminated; new Business contracts are blocked.'); if(!businessName.trim()) return setNotice('Business name is required.'); if(s.businesses.length>=2) return setNotice('Demo limit: PSP can fund exactly two Business contracts here.'); const used=s.businesses.reduce((n,b)=>n+(s.privateLedger[b.id]?.amount||0),0); const limit=s.privateLedger[s.program.id]?.amount||0; if(amt<=0 || used+amt>limit) return setNotice('Private validation failed: Business funding exceeds PSP authorized envelope. Actual threshold remains hidden.'); update(st=>{ const b={id:`PSP-BIZ-${st.businesses.length+1}`,parentId:st.program.id,role:'PSP → Business',name:businessName.trim(),status:'Active',commitment:commit(`business-${businessName}`,amt),availableCommitment:commit(`business-available-${businessName}`,amt),termsHash:hash('fixed-term-funded-non-revocable'),...period(30+st.businesses.length*5,120)}; st.businesses.push(b); st.privateLedger[b.id]={amount:amt}; st.events.unshift(ev('BUSINESS_CONTRACT_CREATED',`PSP funded Business contract for ${b.name}. Amount validated privately.`,{id:b.id,name:b.name,commitment:b.commitment})); return st;}); setBusinessName(s.businesses.length?'LogisticsCo':'RetailCo'); setNotice('Business contract created. Amount is hidden behind commitment.'); }
  function createAgent(){ const bid=selectedBusiness || s.businesses[0]?.id; const b=s.businesses.find(x=>x.id===bid); const amt=money(agentAmount); if(!b) return setNotice('Create/select a Business first.'); if(!agentName.trim()||!agentPurpose.trim()) return setNotice('Agent name and purpose are required.'); const used=businessUsed(s,b.id); const limit=s.privateLedger[b.id]?.amount||0; if(amt<=0 || used+amt>limit) return setNotice('Private validation failed: total Agent authorities exceed Business funded commitment. Admin cannot see the actual amounts.'); update(st=>{ const idx=st.agents.filter(a=>a.parentId===b.id).length+1; const a={id:`${b.id}-AGENT-${idx}`,parentId:b.id,role:'Business → Agent',name:agentName.trim(),purpose:agentPurpose.trim(),status:'Active',commitment:commit(`agent-${agentName}`,amt),remainingCommitment:commit(`agent-remaining-${agentName}`,amt),termsHash:hash(`purpose:${agentPurpose}`),...period(40+idx,95+idx)}; st.agents.push(a); st.privateLedger[a.id]={amount:amt}; st.events.unshift(ev('AGENT_AUTHORITY_CREATED',`${b.name} created Agent authority for purpose: ${a.purpose}.`,{id:a.id,parentId:b.id,purpose:a.purpose,commitment:a.commitment})); return st;}); setNotice('Agent authority created with private amount validation.'); }
  function createReceivable(){ const aid=selectedAgent || s.agents[0]?.id; const a=s.agents.find(x=>x.id===aid); const amt=money(merchantAmount); if(!a) return setNotice('Create/select an Agent first.'); if(!merchantName.trim()) return setNotice('Merchant name is required.'); const used=agentUsed(s,a.id); const limit=s.privateLedger[a.id]?.amount||0; if(amt<=0 || used+amt>limit) return setNotice('Private validation failed: Merchant receivables exceed Agent authority. Actual authority amount is not revealed.'); update(st=>{ const idx=st.receivables.filter(r=>r.parentId===a.id).length+1; const r={id:`${a.id}-RCV-${idx}`,parentId:a.id,role:'Agent → Merchant',merchant:merchantName.trim(),status:'Created',commitment:commit(`merchant-${merchantName}`,amt),claimNullifier:hash(`merchant-nullifier:${a.id}:${merchantName}:${Date.now()}`),createdAt:a.startAt+idx*day,settlementDeadline:a.startAt+(idx+2)*day}; st.receivables.push(r); st.privateLedger[r.id]={amount:amt}; st.events.unshift(ev('MERCHANT_RECEIVABLE_CREATED',`${a.name} paid ${r.merchant}; merchant-level nullifier generated.`,{id:r.id,parentId:a.id,merchant:r.merchant,receivableCommitment:r.commitment,claimNullifier:r.claimNullifier})); return st;}); setNotice('Merchant receivable created. Nullifier exists only at Merchant claim level.'); }
  function settle(){ const pending=s.receivables.filter(r=>r.status==='Created'); if(!pending.length) return setNotice('No pending merchant receivables.'); update(st=>{ const claims=st.receivables.filter(r=>r.status==='Created').slice(0,5); claims.forEach(r=>{ r.status='Settled'; st.nullifiers.push({kind:'Merchant claim',nullifier:r.claimNullifier,context:r.id,consumedAt:new Date().toLocaleTimeString()}); }); const batch={id:`BATCH-${st.batches.length+1}`,status:'Accepted',claims:claims.map(c=>c.id),rollupCommitment:hash(`rollup:${claims.map(c=>c.id).join('|')}`)}; st.batches.push(batch); st.events.unshift(ev('SETTLEMENT_BATCH_ACCEPTED',`Settlement consumed ${claims.length} merchant claim nullifier(s). No batch nullifier is created.`,batch)); return st;}); setNotice('Settlement completed. Only merchant-level claim nullifiers were consumed.'); }
  function replay(){ const used=s.nullifiers[0]; if(!used) return setNotice('Settle at least one merchant claim first.'); update(st=>{ const rejected={id:`REPLAY-${st.batches.length+1}`,status:'Rejected',claimNullifier:used.nullifier,reason:'merchant claim nullifier already consumed'}; st.batches.push(rejected); st.events.unshift(ev('DOUBLE_SETTLEMENT_REJECTED','Replay rejected using merchant-level nullifier.',rejected)); return st;}); setNotice('Replay rejected. Protection is at Merchant claim nullifier level.'); }
  function freeze(){ update(st=>{st.frozen=!st.frozen; st.events.unshift(ev(st.frozen?'PROGRAM_FROZEN':'PROGRAM_UNFROZEN',st.frozen?'Emergency freeze: new downstream actions paused.':'Program unfrozen.')); return st;}); }
  function terminate(){ update(st=>{st.terminated=true; st.events.unshift(ev('PROGRAM_TERMINATED','Ordinary termination: blocks new Business contracts; existing claims may settle.')); return st;}); }
  return <Card className="demo"><h2><Play/> Demo user workflow</h2><p>Enter private amounts. The demo validates limits privately and shows only commitments/nullifiers in the Admin portal.</p>{notice&&<div className="notice">{notice}</div>}<div className="forms"><div className="formBox"><h3>1. Mastercard → PSP</h3><Input label="Private authorized envelope" type="number" value={programAmount} onChange={e=>setProgramAmount(e.target.value)}/><button disabled={!!s.program} onClick={createProgram}><Shield/>Create authorization</button></div><div className="formBox"><h3>2. PSP funds up to 2 Businesses</h3><Input label="Business name" value={businessName} onChange={e=>setBusinessName(e.target.value)}/><Input label="Private funded amount" type="number" value={businessAmount} onChange={e=>setBusinessAmount(e.target.value)}/><button disabled={!s.program||s.businesses.length>=2||s.frozen||s.terminated} onClick={createBusiness}><Landmark/>Create Business contract</button></div><div className="formBox"><h3>3. Business creates Agents</h3><Select label="Business" value={selectedBusiness} onChange={e=>setSelectedBusiness(e.target.value)}><option value="">Select Business</option>{s.businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select><Input label="Agent name" value={agentName} onChange={e=>setAgentName(e.target.value)}/><TextArea label="Agent purpose" value={agentPurpose} onChange={e=>setAgentPurpose(e.target.value)}/><Input label="Private authority amount" type="number" value={agentAmount} onChange={e=>setAgentAmount(e.target.value)}/><button disabled={!s.businesses.length||s.frozen} onClick={createAgent}><UserRoundCog/>Create Agent authority</button></div><div className="formBox"><h3>4. Agent pays Merchant</h3><Select label="Agent" value={selectedAgent} onChange={e=>setSelectedAgent(e.target.value)}><option value="">Select Agent</option>{s.agents.map(a=><option key={a.id} value={a.id}>{a.name} — {a.purpose}</option>)}</Select><Input label="Merchant name" value={merchantName} onChange={e=>setMerchantName(e.target.value)}/><Input label="Private payment amount" type="number" value={merchantAmount} onChange={e=>setMerchantAmount(e.target.value)}/><button disabled={!s.agents.length||s.frozen} onClick={createReceivable}><Send/>Create Merchant receivable</button></div></div><div className="actionRow"><button disabled={!s.receivables.some(r=>r.status==='Created')} onClick={settle}><CheckCircle2/>Settle merchant claims</button><button disabled={!s.nullifiers.length} onClick={replay}><AlertTriangle/>Try double settlement</button><button disabled={!s.program||s.terminated} onClick={terminate}><Ban/>Terminate program</button><button disabled={!s.program||s.terminated} onClick={freeze}><Snowflake/>{s.frozen?'Unfreeze':'Emergency freeze'}</button><button onClick={()=>setS(structuredClone(blank))}><RotateCcw/>Reset</button></div></Card>
}
function Admin({s}){ const contracts=[s.program,...s.businesses,...s.agents].filter(Boolean); return <div className="adminGrid"><Card><h2><Database/> Admin portal: commitment-only records</h2><table><thead><tr><th>ID</th><th>Layer/name</th><th>Status</th><th>Purpose</th><th>Amount view</th><th>Commitment</th></tr></thead><tbody>{contracts.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.role}<br/><b>{x.name}</b></td><td><Badge status={x.id===s.program?.id?(s.frozen?'Frozen':s.terminated?'Terminated':x.status):x.status}/></td><td>{x.purpose||'—'}</td><td><AdminAmountNote/></td><td><code>{short(x.commitment)}</code></td></tr>)}</tbody></table></Card><Card><h2><Receipt/> Merchant receivables</h2><table><thead><tr><th>ID</th><th>Merchant</th><th>Status</th><th>Parent Agent</th><th>Amount view</th><th>Merchant claim nullifier</th></tr></thead><tbody>{s.receivables.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.merchant}</td><td><Badge status={r.status}/></td><td>{r.parentId}</td><td><AdminAmountNote/></td><td><code>{short(r.claimNullifier)}</code></td></tr>)}</tbody></table></Card><Card><h2><LockKeyhole/> Nullifier registry — Merchant level only</h2><table><thead><tr><th>Kind</th><th>Nullifier</th><th>Merchant receivable</th><th>Consumed</th></tr></thead><tbody>{s.nullifiers.map((n,i)=><tr key={i}><td>{n.kind}</td><td><code>{short(n.nullifier)}</code></td><td>{n.context}</td><td>{n.consumedAt}</td></tr>)}</tbody></table></Card><Card><h2><Eye/> Event log</h2><div className="events">{s.events.map(e=><div className="event" key={e.id}><b>{e.type}</b><span>{e.at} — {e.text}</span><code>{JSON.stringify(e.data).slice(0,220)}…</code></div>)}</div></Card></div> }
function App(){ const [tab,setTab]=useState('demo'); const [s,setS]=useState(structuredClone(blank)); const settled=s.receivables.filter(r=>r.status==='Settled').length; const programStatus=s.frozen?'Frozen':s.terminated?'Terminated':s.program?.status||'Not started'; return <main><header className="hero"><div><p className="eyebrow">Interactive demo · private validation · merchant nullifiers only</p><h1>ASL ZK Chain Funded Contract Demo</h1><p>Demo users enter private amounts and names. The app validates thresholds without exposing actual values in the admin portal; admin sees commitments, statuses, purposes, and merchant-level nullifiers.</p></div><div className="tabs"><button className={tab==='demo'?'active':''} onClick={()=>setTab('demo')}><Play/>Demo user</button><button className={tab==='admin'?'active':''} onClick={()=>setTab('admin')}><Database/>Admin portal</button></div></header><section className="kpis"><Card><Shield/><b>{programStatus}</b><span>Mastercard program</span></Card><Card><FileKey2/><b>{s.businesses.length}/2</b><span>PSP-funded Businesses</span></Card><Card><Network/><b>{s.agents.length}</b><span>Agents with purposes</span></Card><Card><Receipt/><b>{s.receivables.length}</b><span>Named Merchant receivables</span></Card><Card><CheckCircle2/><b>{settled}</b><span>Settled claims</span></Card></section>{tab==='demo'?<><DemoActions s={s} setS={setS}/><div className="grid"><Card className="wide"><h2>Live flow graph</h2><Graph s={s}/></Card><Card><h2>Validation model</h2><p>Amounts are entered by the demo user, used for private validation, and immediately represented publicly as commitments.</p><p>Business funding cannot exceed PSP envelope. Agent authorities cannot exceed the selected Business allocation. Merchant receivables cannot exceed Agent authority.</p><p className="warning"><AlertTriangle/> Nullifiers are generated and consumed only for Merchant receivable claims.</p></Card></div></>:<Admin s={s}/>}<Card><h2>Security posture</h2><div className="security"><p><b>No actual amounts in admin/on-chain view:</b> commitments only.</p><p><b>Quantum-safe ready:</b> hash/nullifier-first model with PQ verifier interfaces.</p><p><b>Non-revocation:</b> funded contracts protect downstream parties during the committed period.</p><p><b>Replay protection:</b> merchant claim nullifiers prevent double settlement.</p></div></Card><footer>Docs are bundled under <code>/docs</code>. Demo private values are session-local and intentionally hidden from admin tables.</footer></main> }
createRoot(document.getElementById('root')).render(<App/>);
