// scripts/deploy.js
// Run: npx hardhat run scripts/deploy.js --network sepolia

const hre = require("hardhat");
const fs  = require("fs");
const path = require("path");

async function main() {
  console.log("\n╔══════════════════════════════════════════════════════╗");
  console.log("║   ASL ZK Chain — Sepolia Deployment                  ║");
  console.log("╚══════════════════════════════════════════════════════╝\n");

  const [deployer] = await hre.ethers.getSigners();
  console.log(`  Deployer: ${deployer.address}`);
  const bal = await deployer.getBalance();
  console.log(`  Balance:  ${hre.ethers.utils.formatEther(bal)} ETH\n`);

  // ── 1. Deploy UpstreamVerifier ────────────────────────────────
  console.log("▶ Deploying UpstreamVerifier...");
  const UpstreamVerifier = await hre.ethers.getContractFactory("UpstreamVerifier");
  const upstreamVerifier = await UpstreamVerifier.deploy();
  await upstreamVerifier.deployed();
  console.log(`  ✓ UpstreamVerifier: ${upstreamVerifier.address}`);

  // ── 2. Deploy DownstreamVerifier ──────────────────────────────
  console.log("▶ Deploying DownstreamVerifier...");
  const DownstreamVerifier = await hre.ethers.getContractFactory("DownstreamVerifier");
  const downstreamVerifier = await DownstreamVerifier.deploy();
  await downstreamVerifier.deployed();
  console.log(`  ✓ DownstreamVerifier: ${downstreamVerifier.address}`);

  // ── 3. Deploy ASLDelegationChain ──────────────────────────────
  console.log("▶ Deploying ASLDelegationChain...");
  const Chain = await hre.ethers.getContractFactory("ASLDelegationChain");
  const chain = await Chain.deploy(
    upstreamVerifier.address,
    downstreamVerifier.address
  );
  await chain.deployed();
  console.log(`  ✓ ASLDelegationChain: ${chain.address}`);

  // ── 4. Write config for frontend ──────────────────────────────
  const config = {
    network: "sepolia",
    chainId: 11155111,
    contractAddress: chain.address,
    upstreamVerifierAddress: upstreamVerifier.address,
    downstreamVerifierAddress: downstreamVerifier.address,
    deployedAt: new Date().toISOString(),
    deployer: deployer.address
  };

  fs.writeFileSync(
    path.join(__dirname, "../frontend/config.json"),
    JSON.stringify(config, null, 2)
  );

  fs.writeFileSync(
    path.join(__dirname, "../frontend/config.js"),
    `// Auto-generated by deploy.js — do not edit manually\n` +
    `window.CHAIN_CONFIG = ${JSON.stringify(config, null, 2)};\n`
  );

  console.log("\n  ✓ frontend/config.js written with contract addresses");

  // ── 5. Print summary ──────────────────────────────────────────
  console.log("\n╔══════════════════════════════════════════════════════╗");
  console.log("║   Deployment complete!                                ║");
  console.log("╠══════════════════════════════════════════════════════╣");
  console.log(`║  ASLDelegationChain: ${chain.address}  ║`);
  console.log(`║  Network: Sepolia (chainId 11155111)                  ║`);
  console.log(`║  Verify: https://sepolia.etherscan.io/address/        ║`);
  console.log(`║          ${chain.address}  ║`);
  console.log("╚══════════════════════════════════════════════════════╝\n");
}

main()
  .then(() => process.exit(0))
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
